version: '3'

services:
  db:
    image: postgres:latest
    env_file:
      - .env
    ports:
      - 15432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:4.0-alpine

  app:
    build:
      context: .
    image: nem-per-feina:local
    user: root
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - 8000:8000
    volumes:
      - .:/nem-per-feina/
    entrypoint:
      - invoke
      - wait-for
      - db:5432
      - migrate
      - runserver
      - --debug

  celery:
    build:
      context: .
    image: celery:local
    user: root
    depends_on:
      - db
      - redis
    env_file:
      - .env
    volumes:
      - .:/nem-per-feina/
    entrypoint:
      - invoke
      - wait-for
      - redis:6379
      - wait-for
      - db:5432
      - celery-queues
  flower:
    image: mher/flower:0.9.5
    env_file:
      .env
    ports:
      - 8888:8888


volumes:
  postgres_data:
