version: "3"

services:
  db:
    image: postgres:latest
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
    image: anemperfeina:1.0
    user: root
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - 8000:8000
    volumes:
      - .:/anem-per-feina/
    entrypoint:
      - invoke
      - wait-for
      - db:5432
      - migrate
      - runserver
      - --debug

volumes:
  postgres_data:
