[tool.black]
line-length = 100
include = '\.pyi?$'
exclude = 'venv'
force-exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.pytest_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
| ./*/migrations
'''

[tool.isort]
line_length = 100
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
known_django = 'django'
sections = 'FUTURE,STDLIB,THIRDPARTY,DJANGO,FIRSTPARTY,LOCALFOLDER'
skip='migrations'
known_third_party = 'django,drf_yasg,environ,rest_framework,rest_framework_simplejwt,whitenoise'
