# Generated by Django 3.0.7 on 2021-01-20 14:24

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(blank=True, max_length=128, null=True, verbose_name='Street')),
                ('number', models.CharField(blank=True, max_length=16, null=True, verbose_name='Door Number')),
                ('city', models.CharField(db_index=True, max_length=128, verbose_name='City')),
                ('county', models.CharField(blank=True, max_length=128, null=True, verbose_name='County')),
                ('state', models.CharField(blank=True, max_length=64, null=True, verbose_name='State')),
                ('country', models.CharField(db_index=True, max_length=64, verbose_name='Country')),
                ('postalcode', models.CharField(blank=True, max_length=16, null=True, verbose_name='Postal Code')),
                ('lat', models.FloatField(null=True, verbose_name='Latitude')),
                ('lon', models.FloatField(null=True, verbose_name='Longitude')),
                ('geo_point', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326)),
            ],
        ),
    ]
