# Generated by Django 3.0.7 on 2021-02-11 16:09

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_remove_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(blank=True, max_length=128, null=True, verbose_name='Street')),
                ('city', models.CharField(db_index=True, max_length=128, verbose_name='City')),
                ('county', models.CharField(blank=True, max_length=128, null=True, verbose_name='County')),
                ('state', models.CharField(blank=True, max_length=64, null=True, verbose_name='State')),
                ('country', models.CharField(db_index=True, max_length=64, verbose_name='Country')),
                ('postalcode', models.CharField(blank=True, max_length=16, null=True, verbose_name='Postal Code')),
                ('lat', models.FloatField(null=True, verbose_name='Latitude')),
                ('lon', models.FloatField(null=True, verbose_name='Longitude')),
                ('geo_point', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326)),
                ('user', models.ForeignKey(blank=True, help_text='User address.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='accounts.User', verbose_name='User')),
            ],
            options={
                'unique_together': {('lat', 'lon', 'user')},
            },
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('geolocation.address',),
        ),
    ]
