# Generated by Django 3.0.7 on 2021-02-16 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_user_role'),
        ('geolocation', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='address',
            unique_together={('geo_point', 'user')},
        ),
        migrations.RemoveField(
            model_name='address',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='address',
            name='lon',
        ),
    ]
