# Generated by Django 3.0.7 on 2021-01-25 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geolocation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('geolocation.address',),
        ),
        migrations.RemoveField(
            model_name='address',
            name='number',
        ),
    ]
