# Generated by Django 3.0.7 on 2021-01-25 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geolocation', '0002_auto_20210125_1455'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='address',
            unique_together={('lat', 'lon')},
        ),
    ]
