# Generated by Django 3.0.7 on 2021-01-27 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_user_role'),
        ('geolocation', '0003_auto_20210125_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User address.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='accounts.User', verbose_name='User'),
        ),
    ]
