# Generated by Django 3.0.7 on 2021-01-30 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_user_role'),
        ('geolocation', '0004_address_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='address',
            unique_together={('lat', 'lon', 'user')},
        ),
    ]
