apiVersion: v1
kind: Service
metadata:
  name: {{ include "apf.fullname" . }}
  labels:
    {{- include "apf.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.app.service.port }}
      targetPort: {{ .Values.app.service.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "apf.selectorLabels" . | nindent 4 }}
