apiVersion: v1
kind: Secret
metadata:
  name: django-secrets
data:
  SECRET_KEY: c2VjcmV0
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
data:
  POSTGRES_PASSWORD: "czNjcmV0"
---
apiVersion: v1
kind: Secret
metadata:
  name: telegram-secrets
data:
  TELEGRAM_TOKEN: "xxxx"