apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "apf.fullname" . }}-cert
spec:
  secretName: {{ include "apf.fullname" . }}-cert
  issuerRef:
    kind: ClusterIssuer
    name: {{ .Values.certificate.issuername }}
  commonName: {{ .Values.certificate.hostname }}
  dnsNames:
    - {{ .Values.certificate.hostname }}