{{- if .Values.ingress.enabled -}}
{{- $fullName := include "apf.fullname" . -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "apf.labels" . | nindent 4 }}
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web, websecure
    cert-manager.io/cluster-issuer: {{ .Values.certificate.issuername | quote }}
spec:
  backend:
    serviceName: {{ $fullName }}
    servicePort: {{ .Values.ingress.app.port }}
  {{- if .Values.ingress.tls }}
  tls:
      secretName: {{ $fullName }}-cert
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ . }}
            backend:
              serviceName: {{ .serviceName }}
              servicePort: {{ .servicePort }}
          {{- end }}
    {{- end }}
  {{- end }}
