apiVersion: v1
kind: Secret
metadata:
  name: {{ include "apf.fullname" . }}
  labels:
    app: {{ template "apf.name" . }}
    chart: {{ template "apf.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
data:
    BASE_URL: {{ .Values.baseUrl | b64enc | quote }}
    BASE_EMAIL: {{ .Values.baseEmail | b64enc | quote }}
    DEBUG: {{ .Values.app.debug | b64enc | quote }}
    SILENCED_SYSTEM_CHECKS: {{ .Values.app.silencedSystemChecks | b64enc | quote }}
    LOG_LEVEL: {{ .Values.app.log_level | b64enc | quote }}
    SECRET_KEY: {{ required "secret key is needed" .Values.app.secretKey | b64enc | quote }}
    # Postgres
    POSTGRES_DB: {{ .Values.postgresql.postgresqlDatabase | b64enc | quote }}
    POSTGRES_USER: {{ .Values.postgresql.postgresqlUsername | b64enc | quote }}
    POSTGRES_HOST: {{ printf "%s-postgresql" (include "apf.fullname" .) | b64enc | quote }}
    POSTGRES_PORT: {{ .Values.postgresql.service.port | b64enc | quote }}
    POSTGRES_PASSWORD: {{ required "postgres password is needed" .Values.postgresql.postgresqlPassword | b64enc | quote }}
    # Celery
    CELERY_BROKER_PROTOCOL: {{ .Values.celery.broker.protocol | b64enc | quote }}
    CELERY_BROKER_HOST: {{ printf "%s-redis-master" (include "apf.fullname" .) | b64enc | quote }}
    CELERY_BROKER_PORT: {{ .Values.redis.redisPort | b64enc | quote }}
    CELERY_BROKER_DB: {{ .Values.redis.db | b64enc | quote }}
    CELERY_REDIRECT_STDOUTS_LEVEL: {{ .Values.celery.stdouts_level | b64enc | quote }}
    # Telegram
    TELEGRAM_TOKEN: {{ .Values.notifications.telegram.token | b64enc | quote }}
    NOTIF_TELEGRAM_ENABLED: {{ .Values.notifications.telegram.enabled | b64enc | quote }}
    TELEGRAM_CHAT_IDS: {{ .Values.notifications.telegram.chatIds | b64enc | quote }}
    # Twitter
    NOTIF_TWITTER_ENABLED: {{ .Values.notifications.twitter.enabled | b64enc | quote }}
    TWITTER_API_KEY: {{ .Values.notifications.twitter.apiKey | b64enc | quote }}
    TWITTER_API_SECRET: {{ .Values.notifications.twitter.apiSecret | b64enc | quote }}
    TWITTER_ACCESS_TOKEN: {{ .Values.notifications.twitter.accessToken | b64enc | quote }}
    TWITTER_ACCESS_TOKEN_SECRET: {{ .Values.notifications.twitter.accessTokenSecret | b64enc | quote }}
    # Social Auth
    SOCIAL_AUTH_GITHUB_KEY: {{ .Values.socialAuth.githubKey | b64enc | quote }}
    SOCIAL_AUTH_GITHUB_SECRET: {{ .Values.socialAuth.githubSecret | b64enc | quote }}
    # Recaptcha
    RECAPTCHA_PUBLIC_KEY: {{ .Values.recaptcha.publicKey | b64enc | quote }}
    RECAPTCHA_PRIVATE_KEY: {{ .Values.recaptcha.privateKey | b64enc | quote }}
    # Sentry
    SENTRY_URL: {{ .Values.sentry.dsn | b64enc | quote }}