# Generated by Django 3.0.7 on 2020-10-28 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobsapp', '0009_auto_20201014_0629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='salary',
        ),
    ]
