# Generated by Django 3.0.7 on 2020-10-30 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsapp', '0010_delete_applicant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='salary',
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['location'], name='jobsapp_job_locatio_c3cbdf_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['category'], name='jobsapp_job_categor_22770c_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['type'], name='jobsapp_job_type_c3b0db_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['title'], name='jobsapp_job_title_51142e_idx'),
        ),
    ]
