# Generated by Django 3.0.7 on 2020-10-28 14:19

from django.db import migrations
import inclusive_django_range_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('jobsapp', '0010_remove_job_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='salary',
            field=inclusive_django_range_fields.fields.InclusiveIntegerRangeField(null=True),
        ),
    ]
