# Generated by Django 3.0.7 on 2020-10-28 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobsapp', '0010_delete_applicant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='salary',
        ),
    ]
