# Generated by Django 3.0.7 on 2020-10-28 15:56

from django.db import migrations
import inclusive_django_range_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('jobsapp', '0011_remove_job_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='salary',
            field=inclusive_django_range_fields.fields.InclusiveIntegerRangeField(help_text='Minimum and maximum annual salary for this job.', null=True, verbose_name='Salary'),
        ),
    ]
