# Generated by Django 3.0.7 on 2020-11-03 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsapp', '0013_job_remote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='salary',
        ),
        migrations.AddField(
            model_name='job',
            name='apply_url',
            field=models.URLField(default='', help_text='Users will apply on your website.', verbose_name='Apply URL'),
        ),
        migrations.AlterField(
            model_name='job',
            name='category',
            field=models.CharField(choices=[('web-design', 'Web design'), ('graphic-design', 'Graphic design'), ('web-development', 'Web development')], help_text='Category clasification.', max_length=100, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='job',
            name='last_date',
            field=models.DateField(help_text='Last date.', verbose_name='Last date'),
        ),
    ]
