# Generated by Django 3.0.7 on 2020-11-04 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsapp', '0015_job_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='category',
            field=models.CharField(choices=[('web-design', 'Web design'), ('graphic-design', 'Graphic design'), ('software-developer', 'Sofware developer'), ('data-analyst', 'Data analyst'), ('mobile-android-junior-developer', 'Junior Mobile developer Android'), ('mobile-android-medior-developer', 'Medior Mobile developer Android'), ('mobile-android-senior-developer', 'Senior Mobile developer Android'), ('mobile-ios-junior-developer', 'Junior Mobile developer iOS'), ('mobile-ios-medior-developer', 'Medior Mobile developer iOS'), ('mobile-ios-senior-developer', 'Senior Mobile developer iOS'), ('frontend-junior-developer', 'Junior Frontend developer'), ('frontend-medior-developer', 'Medior Frontend developer'), ('frontend-senior-developer', 'Senior Frontend developer'), ('backend-junior-developer', 'Junior Backend developer'), ('backend-medior-developer', 'Medior Backend developer'), ('backend-senior-developer', 'Senior Backend developer'), ('fullstack-junior-developer', 'Junior Fullstack developer'), ('fullstack-medior-developer', 'Medior Fullstack developer'), ('fullstack-senior-developer', 'Senior Fullstack developer'), ('product-owner', 'Product Owner'), ('project-manager', 'Project Manager'), ('lead-software-engineer', 'Lead software engineer'), ('security-specialist', 'Security specialist'), ('sysadmin', 'Sysadmin'), ('devops', 'Devops'), ('database-administrator', 'Database administrator')], help_text='Category clasification.', max_length=100, verbose_name='Category'),
        ),
    ]
