# Generated by Django 3.0.7 on 2020-11-04 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsapp', '0015_job_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='category',
            field=models.CharField(choices=[('web-design', 'Web design'), ('graphic-design', 'Graphic design'), ('software-developer', 'Sofware developer'), ('data-analyst', 'Data analyst'), ('mobile-android-developer', 'Android mobile developer'), ('mobile-ios-developer', 'iOS mobile developer'), ('frontend-developer', 'Frontend developer'), ('backend-developer', 'Backend developer'), ('fullstack-developer', 'Fullstack developer'), ('product-owner', 'Product Owner'), ('project-manager', 'Project Manager'), ('lead-software-engineer', 'Lead software engineer'), ('security-specialist', 'Security specialist'), ('sysadmin', 'Sysadmin'), ('devops', 'Devops'), ('database-administrator', 'Database administrator')], help_text='Category clasification.', max_length=100, verbose_name='Category'),
        ),
    ]
