# Generated by Django 3.0.7 on 2020-11-25 09:39

from django.db import migrations
import jobsapp.fields


class Migration(migrations.Migration):

    dependencies = [
        ('jobsapp', '0018_auto_20201104_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='apply_url',
            field=jobsapp.fields.JobsURLField(default='', help_text='Users will apply on your website.', max_length=500, verbose_name='Apply URL'),
        ),
    ]
