# Generated by Django 3.0.7 on 2020-11-25 18:02

from django.db import migrations
import jobsapp.fields


class Migration(migrations.Migration):

    dependencies = [
        ('jobsapp', '0019_auto_20201125_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='company_description',
            field=jobsapp.fields.SanitizedHTMLField(help_text='Company description, activity,...', max_length=300, verbose_name='Company description'),
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=jobsapp.fields.SanitizedHTMLField(help_text='Long job description.', verbose_name='Description'),
        ),
    ]
