# Generated by Django 3.0.7 on 2021-02-11 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geolocation', '0001_initial'),
        ('jobsapp', '0020_auto_20201125_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='address',
            field=models.ForeignKey(blank=True, help_text='Location for this job position.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='geolocation.Address', verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.CharField(default='', help_text='Location for this job position.', max_length=150, verbose_name='Location'),
        ),
    ]
