# Generated by Django 3.0.7 on 2021-01-24 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsapp', '0021_job_geo_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.CharField(default='', help_text='Location for this job position.', max_length=150, verbose_name='Location'),
        ),
    ]
