apiVersion: v2
name: npf
description: Nem per feina Chart
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.2.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
appVersion: 1.16.0

dependencies:
    - name: redis
      version: 11.0.6
      repository: https://charts.bitnami.com/bitnami
    - name: postgresql
      version: 9.8.1
      repository: https://charts.bitnami.com/bitnami
