# Performs a code validation reviewing format and checking types
name: code-check

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # install testing dev libraries
          pip install -r requirements-test.txt
      - name: Run source code analysis and code format
        run: |
          pre-commit run --all
      - name: Run typing tests //will not raise
        continue-on-error: true
        run: |
          mypy $(find . | grep '.py$' | grep -ve './*/migrations')
        env:
          SECRET_KEY: mypy
          POSTGRES_PASSWORD: mypy
