# Performs a code validation reviewing format and checking types
name: tests

on: [push]
# on:
#   push:
#     branches:
#       - master
#   pull_request:
#     branches:
#       - master
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Execute tests
        run: make test